config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [ :edit, :show, :destroy]
  def index
    @flats = Flat.all
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@restaurant)
    else
      render :new
    end
  end

  def new
    @flat = Flat.new
  end

  def edit

  end

  def show
  end

  def update

  end

  def destroy

  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :number_of_guests, :price_per_night)
  end

  def find_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<br>
<h1>All our flats</h1>
<br>
<ul>
<% @flats.each do |flat| %>
  <li><%= link_to flat.name, flat_path(flat) %></li>
<% end %>
</ul>

app/views/flats/new.html.erb
<h1>Add a new flat</h1>


<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Add a flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<h2><%= @flat.address %></h2>
<p>Description: <%= @flat.description %></p>
<p>Price: <%= @flat.price_per_night %> €</p>
<p>Guests: <%= @flat.number_of_guests %></p>

<%= link_to 'Back', flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <br>
  <br>
  <div class='container'>
    <div class='row'>
      <div class='col-10'>
        <%= link_to 'Simple AirBnB', flats_path %>
        <%= link_to 'Add new flat', new_flat_path %>
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>